#calculator program using python
 num1 = input("enter first number: ")
 num2 = input("enter second number: ")
 print("sum of {0} and {1} is: {2}".format(num1, num2, int(num1) + int(num2)))
 print("difference of {0} and {1} is: {2}".format(num1, num2, int(num1) - int(num2)))
 print("product of {0} and {1} is: {2}".format(num1, num2, int(num1) * int(num2)))
 print("quotient of {0} and {1} is: {2}".format(num1, num2, int(num1) / int(num2)))
 print("remainder of {0} and {1} is: {2}".format(num1, num2, int(num1) % int(num2)))
 print("power of {0} and {1} is: {2}".format(num1, num2, int(num1) ** int(num2)))
 print("square root of {0} is: {1}".format(num1, int(num1) ** 0.5))
 print("absolute value of {0} is: {1}".format(num1, abs(int(num1))))
 print("floor value of {0} is: {1}".format(num1, math.floor(int(num1))))
 print("ceiling value of {0} is: {1}".format(num1, math.ceil(int(num1))))
 print("round value of {0} is: {1}".format(num1, round(int(num1))))
 print("square root of {0} is: {1}".format(num1, math.sqrt(int(num1))))
 print("sin value of {0} is: {1}".format(num1, math.sin(int(num1))))
 print("cos value of {0} is: {1}".format(num1, math.cos(int(num1))))